import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Shield } from "lucide-react";

interface TermsConsentDialogProps {
  open: boolean;
  onAccept: () => void;
  onDismiss: () => void;
}

const TermsConsentDialog = ({ open, onAccept, onDismiss }: TermsConsentDialogProps) => {
  const [agreeTerms, setAgreeTerms] = useState(false);

  return (
    <Dialog open={open} onOpenChange={(v) => { if (!v) onDismiss(); }}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <Shield className="h-5 w-5 text-primary" />
            <DialogTitle className="text-lg">User Consent & Data Usage Agreement</DialogTitle>
          </div>
          <DialogDescription className="text-sm">
            Please review and accept before continuing.
          </DialogDescription>
        </DialogHeader>

        <ScrollArea className="h-56 rounded-md border p-4 text-sm text-muted-foreground leading-relaxed">
          <p className="mb-4">
            By accessing and using this platform, you acknowledge and provide your informed and voluntary consent for the collection, storage, and processing of your personal and interview-related information. This includes your name, email address, phone number, login credentials (which will be securely stored in encrypted form), as well as details related to your interview sessions such as your responses, selected role, company name, interaction data, performance scores, and feedback reports generated by the system. You understand that this information is essential for delivering the core functionality of the platform, including conducting AI-powered interview sessions, generating personalized feedback, maintaining your performance history in the dashboard, and improving the overall quality and intelligence of the system.
          </p>
          <p className="mb-4">
            You further agree that your interview responses and performance data may be retained for future reference and may be analyzed in an anonymized and aggregated manner to enhance the platform's features, including question generation, evaluation accuracy, and user experience improvements. While your personal data will not be sold or shared with unauthorized third parties, you acknowledge that it may be processed by trusted service providers such as cloud hosting services and payment gateways strictly for the purpose of delivering the platform's services. The platform undertakes reasonable security measures, including encryption and secure storage practices, to protect your data from unauthorized access, misuse, or disclosure.
          </p>
          <p>
            You retain the right to access your personal data, request corrections to inaccurate information, and request deletion of your data at any time, subject to applicable legal and operational requirements. By proceeding, you confirm that you have read and understood the Terms and Conditions and Privacy Policy of the platform, and you explicitly consent to the collection and use of your personal and interview data as described herein, including the use of anonymized data for research, analytics, and system improvement purposes. You also understand that you may withdraw your consent at any time by discontinuing use of the platform or by formally requesting data deletion through the provided support channels.
          </p>
        </ScrollArea>

        <div className="space-y-3 mt-2">
          <p className="text-sm text-muted-foreground leading-snug">
            By accepting, you also consent to the following:
          </p>
          <ul className="space-y-2 pl-1">
            <li className="flex items-start gap-2 text-sm text-muted-foreground leading-snug">
              <span className="text-primary mt-0.5">•</span>
              The collection and use of my personal and interview data as described above
            </li>
            <li className="flex items-start gap-2 text-sm text-muted-foreground leading-snug">
              <span className="text-primary mt-0.5">•</span>
              My anonymized data being used for platform improvement and analytics
            </li>
          </ul>

          <div className="flex items-start gap-3 pt-2 border-t border-border/60">
            <Checkbox
              id="terms-agree"
              checked={agreeTerms}
              onCheckedChange={(v) => setAgreeTerms(v === true)}
              className="mt-0.5"
            />
            <label htmlFor="terms-agree" className="text-sm cursor-pointer leading-snug font-medium">
              I agree to the Terms and Conditions and Privacy Policy
            </label>
          </div>
        </div>

        <div className="flex justify-end gap-2 mt-2">
          <Button variant="ghost" size="sm" onClick={onDismiss}>
            Later
          </Button>
          <Button size="sm" disabled={!agreeTerms} onClick={onAccept}>
            Accept & Continue
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default TermsConsentDialog;
